"use client"

import { Bar, BarChart, CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart"
import { efficiencyData, trendData } from "@/lib/demo-data"
import { SectionEyebrow } from "./header"
const scoreConfig = { score: { label: "本剧", color: "var(--chart-1)" }, benchmark: { label: "行业基准", color: "var(--chart-2)" } } satisfies ChartConfig
const timeConfig = { manual: { label: "传统流程", color: "var(--chart-3)" }, dna: { label: "PlotDNA", color: "var(--chart-1)" } } satisfies ChartConfig
export function AnalyticsView() { return <section className="flex flex-col gap-8"><div className="flex max-w-3xl flex-col gap-3"><SectionEyebrow>Narrative Intelligence</SectionEyebrow><h1 className="text-balance text-3xl font-semibold tracking-tight md:text-5xl">让创作判断变得<span className="text-primary">可解释。</span></h1><p className="leading-relaxed text-muted-foreground">从节拍贡献、提示词一致性与制作效率三个维度，读取这次重组的健康度。</p></div><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>叙事节拍强度</CardTitle><CardDescription>当前版本与平台短剧高完播基准对比</CardDescription></CardHeader><CardContent><ChartContainer config={scoreConfig} className="h-72 w-full"><LineChart accessibilityLayer data={trendData}><CartesianGrid vertical={false} /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis domain={[50,100]} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Line dataKey="score" stroke="var(--color-score)" strokeWidth={3} dot /><Line dataKey="benchmark" stroke="var(--color-benchmark)" strokeDasharray="5 5" /></LineChart></ChartContainer></CardContent></Card><Card><CardHeader><CardTitle>制作时间对比</CardTitle><CardDescription>分钟 / 单支 60 秒概念短片</CardDescription></CardHeader><CardContent><ChartContainer config={timeConfig} className="h-72 w-full"><BarChart accessibilityLayer data={efficiencyData}><CartesianGrid vertical={false} /><XAxis dataKey="stage" tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="manual" fill="var(--color-manual)" radius={5} /><Bar dataKey="dna" fill="var(--color-dna)" radius={5} /></BarChart></ChartContainer></CardContent></Card></div><Card><CardHeader><CardTitle>节拍贡献矩阵</CardTitle><CardDescription>颜色越亮，代表该 DNA 来源对当前幕的影响越强。</CardDescription></CardHeader><CardContent className="overflow-x-auto"><div className="grid min-w-2xl grid-cols-[140px_repeat(6,1fr)] gap-2 text-center text-xs"><span /><>{[1,2,3,4,5,6].map((n) => <span key={n} className="text-muted-foreground">第 {n} 幕</span>)}</>{["结构骨架","情绪引擎","视觉语法"].map((row, ri) => <React.Fragment key={row}><span className="py-4 text-left font-medium">{row}</span>{[82,64,91,73,88,78].map((v, i) => <span key={i} className="rounded-md bg-primary p-4 text-primary-foreground" style={{ opacity: Math.max(.3, (v-ri*9)/100) }}>{v-ri*9}</span>)}</React.Fragment>)}</div></CardContent></Card></section> }
import * as React from "react"
