"use client"

import { Check, Download, Eye, FileArchive, FileJson, FileSpreadsheet, FileText, History } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { exportFormats, exportHistory } from "@/lib/workspace-data"
import type { GeneratedScriptResult } from "@/types/dna"

const icons={md:FileText,json:FileJson,comfy:FileJson,csv:FileSpreadsheet,trace:FileArchive}
export function ExportCenter({result,onExportAll,onDownload}:{result:GeneratedScriptResult;onExportAll:()=>void;onDownload:(name:string,value:string,type?:string)=>void}){const exportOne=(id:string)=>{if(id==="md")onDownload("plotdna-script.md",`# ${result.title}\n\n${result.logline}\n\n${result.scenes.map(s=>`## S${s.id} ${s.title}\n${s.shot}\n\n${s.dialogue}`).join("\n\n")}`,"text/markdown");else if(id==="csv")onDownload("shots.csv",`scene,time,title,camera,node\n${result.scenes.map(s=>`${s.id},${s.time},${s.title},${s.camera},${s.node}`).join("\n")}`,"text/csv");else onDownload(`plotdna-${id}.json`,JSON.stringify({format:id,title:result.title,scenes:result.scenes},null,2),"application/json");toast.success("导出任务已创建")};return <section className="flex flex-col gap-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs text-muted-foreground">DELIVERY CENTER / v0.8.3</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">导出与交付中心</h1><p className="mt-2 max-w-2xl text-muted-foreground">针对编剧、制片、AI 视频与合规审阅分别生成结构化交付物，并保留版本与来源信息。</p></div><Button onClick={onExportAll}><Download data-icon="inline-start"/>导出完整项目包</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{exportFormats.map(f=>{const Icon=icons[f.id as keyof typeof icons];return <Card key={f.id}><CardHeader><div className="mb-3 flex size-10 items-center justify-center rounded-lg bg-muted"><Icon className="size-5"/></div><CardTitle>{f.name} <span className="font-mono text-sm text-muted-foreground">{f.extension}</span></CardTitle><CardDescription>{f.description}</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{f.includes.map(v=><div key={v} className="flex items-center gap-2 text-sm"><Check className="size-4 text-muted-foreground"/>{v}</div>)}{f.lastExport&&<p className="pt-2 text-xs text-muted-foreground">上次导出：{f.lastExport}</p>}</CardContent><CardFooter className="justify-between"><Preview format={f.name}/><Button size="sm" onClick={()=>exportOne(f.id)}>下载</Button></CardFooter></Card>})}</div><Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="size-4"/>导出历史</CardTitle><CardDescription>当前项目最近生成的交付记录。</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>文件名</TableHead><TableHead>格式</TableHead><TableHead>版本</TableHead><TableHead>时间</TableHead><TableHead className="text-right">大小</TableHead></TableRow></TableHeader><TableBody>{exportHistory.map(r=><TableRow key={r.id}><TableCell className="font-medium">{r.name}</TableCell><TableCell><Badge variant="outline">{r.format}</Badge></TableCell><TableCell className="font-mono">{r.version}</TableCell><TableCell>{r.createdAt}</TableCell><TableCell className="text-right">{r.size}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></section>}
function Preview({format}:{format:string}){return <Dialog><DialogTrigger render={<Button variant="ghost" size="sm"/>}><Eye data-icon="inline-start"/>预览</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{format} · 内容预览</DialogTitle><DialogDescription>导出前确认本格式的结构与元数据。</DialogDescription></DialogHeader><pre className="max-h-80 overflow-auto rounded-lg bg-muted p-4 font-mono text-xs leading-relaxed">{`PROJECT: 第七分钟的证人\nVERSION: v0.8.3\nSOURCE_IDS: SRC-001, SRC-002, SRC-003\nSCENES: 6\nORIGINALITY: 91/100\nLINEAGE_INCLUDED: true`}</pre></DialogContent></Dialog>}
