"use client"

import { ArrowRight, CheckCircle2, FileSearch, GitBranch, ShieldCheck } from "lucide-react"
import { useState } from "react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { lineagePaths, sourceAssets } from "@/lib/workspace-data"

export function LineageView(){const [source,setSource]=useState("all"),[scene,setScene]=useState("all");const rows=lineagePaths.filter(p=>(source==="all"||p.sourceId===source)&&(scene==="all"||String(p.sceneId)===scene));return <section className="flex flex-col gap-6"><div><p className="font-mono text-xs text-muted-foreground">NARRATIVE LINEAGE GRAPH</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">来源溯源追踪</h1><p className="mt-2 max-w-3xl text-muted-foreground">解释每个镜头为何产生：它来自哪份素材、提取了什么抽象功能、经过哪个槽位，以及最终进入了哪些交付文件。</p></div><Alert><ShieldCheck/><AlertTitle>原创性声明</AlertTitle><AlertDescription>当前版本仅保留节拍、情绪动力和视觉函数；人物、专名、具体事件与原始表达均已隔离重写。以下数据为产品演示追踪记录。</AlertDescription></Alert>
<div className="flex flex-col gap-3 rounded-lg border bg-card p-4 md:flex-row md:items-center"><FileSearch className="size-5 text-muted-foreground"/><Select value={source} onValueChange={v=>v&&setSource(v)}><SelectTrigger className="md:w-64"><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="all">全部来源</SelectItem>{sourceAssets.map(s=><SelectItem key={s.id} value={s.id}>{s.id} · {s.name}</SelectItem>)}</SelectGroup></SelectContent></Select><Select value={scene} onValueChange={v=>v&&setScene(v)}><SelectTrigger className="md:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="all">全部分镜</SelectItem>{[1,2,3,4,5,6].map(n=><SelectItem key={n} value={String(n)}>场景 S{n}</SelectItem>)}</SelectGroup></SelectContent></Select><Badge variant="secondary">{rows.length} 条有效路径</Badge></div>
<div className="flex flex-col gap-4">{rows.map(path=><Card key={path.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><GitBranch className="size-4"/>路径 {path.id} · 场景 S{path.sceneId}</CardTitle><CardDescription>{path.transform} · 来源贡献 {path.contribution}%</CardDescription></div><div className="flex items-center gap-3"><Progress value={path.contribution} className="w-24"/><Badge variant="outline">置信度 {path.nodes[3].confidence}%</Badge></div></div></CardHeader><CardContent><div className="grid gap-2 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr_auto_1fr] lg:items-stretch">{path.nodes.map((node,i)=><div key={node.id} className="contents"><button className="flex min-w-0 flex-col gap-2 rounded-lg border p-3 text-left transition-colors hover:bg-muted"><div className="flex items-center justify-between gap-2"><Badge variant="secondary">{node.stage}</Badge>{node.risk==="低"?<CheckCircle2 className="size-4 text-muted-foreground"/>:<Badge variant="outline">注意</Badge>}</div><p className="truncate text-sm font-medium">{node.label}</p><p className="text-xs leading-relaxed text-muted-foreground">{node.meta}</p><span className="font-mono text-[11px] text-muted-foreground">CONF {node.confidence}%</span></button>{i<path.nodes.length-1&&<span className="hidden items-center text-muted-foreground lg:flex"><ArrowRight className="size-4"/></span>}</div>)}</div></CardContent></Card>)}</div></section>}
