"use client"

import { FileText, Globe2, Library, Link2, Plus, Upload } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { sourceAssets as initialAssets } from "@/lib/workspace-data"
import type { SourceAsset } from "@/types/dna"

export function SourceLibrary({ onExtract }:{ onExtract:()=>void }) { const [assets,setAssets]=useState(initialAssets); const add=(type:SourceAsset["type"])=>{const asset:SourceAsset={id:`SRC-00${assets.length+1}`,name:type==="URL"?"新导入的参考页面":type==="文本"?"粘贴的创作笔记":"新上传素材.pdf",type,size:type==="URL"?"网页":"12 KB",words:1840,status:"已解析",createdAt:"刚刚",tags:["新素材","待标注"],citations:0,summary:"系统已完成初步清洗，可进入 DNA 拆解。"};setAssets([asset,...assets]);toast.success(`${asset.id} 已完成解析`)}; return <section className="flex flex-col gap-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs text-muted-foreground">SOURCE INGESTION / {String(assets.length).padStart(3,"0")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">素材库与导入中心</h1><p className="mt-2 max-w-2xl text-muted-foreground">统一接收剧本、网页、访谈和世界观设定。每份素材都有独立来源 ID，后续引用自动进入血缘追踪。</p></div><ImportDialog onAdd={add}/></div>
 <div className="grid gap-3 md:grid-cols-3">{[
  { label: "已解析", value: assets.filter(a=>a.status==="已解析").length, icon: FileText },
  { label: "总字数", value: assets.reduce((n,a)=>n+a.words,0).toLocaleString(), icon: Library },
  { label: "被引用", value: assets.reduce((n,a)=>n+a.citations,0), icon: Link2 },
 ].map(metric=>{const Icon=metric.icon;return <Card key={metric.label}><CardContent className="flex items-center gap-3 py-5"><Icon className="size-5 text-muted-foreground"/><div><p className="font-mono text-2xl font-semibold">{metric.value}</p><p className="text-xs text-muted-foreground">{metric.label}</p></div></CardContent></Card>})}</div>
 <Card><CardHeader><CardTitle>项目素材</CardTitle><CardDescription>所有指标均为当前演示项目的模拟解析结果。</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{assets.map(a=><div key={a.id} className="flex flex-col gap-4 rounded-lg border p-4 lg:flex-row lg:items-center"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-muted">{a.type==="URL"?<Globe2 className="size-5"/>:<FileText className="size-5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{a.name}</p><Badge variant="outline">{a.type}</Badge><Badge variant={a.status==="已解析"?"secondary":"outline"}>{a.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{a.summary}</p><div className="mt-2 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>{a.id}</span><span>· {a.words.toLocaleString()} 字</span><span>· {a.createdAt}</span><span>· 引用 {a.citations} 次</span></div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>toast.info(`${a.id} 来源详情已记录`)}>查看来源</Button><Button size="sm" onClick={onExtract}>进入拆解</Button></div></div>)}</CardContent></Card></section> }
function ImportDialog({onAdd}:{onAdd:(type:SourceAsset["type"])=>void}){return <Dialog><DialogTrigger render={<Button/>}><Plus data-icon="inline-start"/>导入新素材</DialogTrigger><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>导入到项目素材库</DialogTitle><DialogDescription>本演示会模拟解析并分配可追踪的来源 ID，不会上传真实文件。</DialogDescription></DialogHeader><Tabs defaultValue="text"><TabsList><TabsTrigger value="text">粘贴文本</TabsTrigger><TabsTrigger value="url">网页 URL</TabsTrigger><TabsTrigger value="file">上传文件</TabsTrigger></TabsList><TabsContent value="text" className="flex flex-col gap-3"><Textarea rows={8} placeholder="粘贴剧本、采访、创作笔记或设定文本…"/><Button onClick={()=>onAdd("文本")}>解析并导入</Button></TabsContent><TabsContent value="url" className="flex flex-col gap-3"><Input placeholder="https://example.com/reference"/><Button onClick={()=>onAdd("URL")}><Globe2 data-icon="inline-start"/>抓取并解析</Button></TabsContent><TabsContent value="file" className="flex flex-col items-center gap-4 rounded-lg border border-dashed p-10 text-center"><Upload className="size-8 text-muted-foreground"/><div><p className="font-medium">拖入 PDF、DOCX 或 TXT</p><p className="text-sm text-muted-foreground">单文件上限 20 MB</p></div><Button variant="outline" onClick={()=>onAdd("PDF")}>选择演示文件</Button></TabsContent></Tabs></DialogContent></Dialog>}
